-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 12:38:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pianoroom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pianoroom` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pianoroom` ;

-- -----------------------------------------------------
-- Table `pianoroom`.`major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`major` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`major` (
  `id` INT NOT NULL,
  `major_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pianoroom`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`user` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `major_id` INT NULL DEFAULT NULL,
  `level` INT NOT NULL,
  `imageurl` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_major_id_idx` (`major_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_major_id`
    FOREIGN KEY (`major_id`)
    REFERENCES `pianoroom`.`major` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pianoroom`.`business_hour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`business_hour` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`business_hour` (
  `room_id` INT NOT NULL,
  `day_of_week` VARCHAR(45) NOT NULL,
  `opening_time` TIME NOT NULL,
  `closing_time` TIME NOT NULL,
  INDEX `fk_businesshr_room_id_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_businesshr_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `pianoroom`.`room` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pianoroom`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`room` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dist` VARCHAR(60) NOT NULL,
  `name` VARCHAR(60) NOT NULL,
  `type` VARCHAR(60) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `pianoroom`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`reservation` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `checkin` TIMESTAMP NULL DEFAULT NULL,
  `checkout` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reservation_room_id_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `pianoroom`.`room` (`id`),
  CONSTRAINT `fk_reservation_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pianoroom`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- 建立 major
-- -----------------------------------------------------
insert into pianoroom.major(id, major_name)
values (1, '鋼琴'), (2, '小提琴'), (3, '中提琴'), (4, '大提琴'), 
	   (5, '低音提琴'), (6, '長笛'), (7, '雙簧管'), (8, '單簧管'), (9, '低音管'), 
       (10, '法國號'), (11, '小號'), (12, '長號'), (13, '低音號'), (14, '打擊'), 
       (15, '聲樂'), (16, '作曲'), (17, '其他');
       
-- -----------------------------------------------------
-- 建立 user
-- -----------------------------------------------------
insert into pianoroom.user(email, password, name, major_id, level) 
values ('admin@gmail.com', 'abc123', 'Admin', 2, 1),
	   ('abc12345678@gmail.com', 'abc12345678', 'Amy', 1, 2),
	   ('87654321cba@gmail.com', '87654321cba', 'Ben', 2, 2),
       ('1qazwsxedc@gmail.com', '1qazwsxedc', 'Carl', 3, 2);

-- -----------------------------------------------------
-- 建立 room
-- -----------------------------------------------------
insert into pianoroom.room(dist, name, type, latitude, longitude) 
values ('台北民生校', '503', '教學琴房', 25.05924488253332, 121.5425743262388),
	   ('台北民生校', '508', '練習琴房', 25.057972977895904, 121.54228159001215),
	   ('台北中正校', '貝多芬室', '練習琴房', 25.045608340381392, 121.52511466517534);

-- -----------------------------------------------------
-- 建立 business_hour
-- -----------------------------------------------------
insert into pianoroom.business_hour(room_id, day_of_week, opening_time, closing_time) 
values ('1', '1', '10:00:00', '22:00:00'), ('1', '2', '10:00:00', '22:00:00'), ('1', '3', '10:00:00', '22:00:00'), ('1', '4', '10:00:00', '22:00:00'), ('1', '5', '10:00:00', '22:00:00'),
       ('2', '2', '10:00:00', '20:00:00'), ('2', '3', '10:00:00', '20:00:00'), ('2', '4', '10:00:00', '20:00:00'), ('2', '5', '10:00:00', '20:00:00'), ('2', '6', '10:00:00', '20:00:00'),
	   ('3', '2', '08:00:00', '20:00:00'), ('3', '3', '08:00:00', '20:00:00'), ('3', '4', '08:00:00', '20:00:00'), ('3', '5', '08:00:00', '20:00:00'), ('3', '6', '08:00:00', '20:00:00'), ('3', '7', '08:00:00', '20:00:00');

-- -----------------------------------------------------
-- 建立 reservation
-- -----------------------------------------------------
insert into pianoroom.reservation(user_id ,room_id, start_time, end_time, checkin, checkout)
values ('1', '1', '2023-12-19 16:00:00', '2023-12-19 17:00:00', '2023-12-19 16:00:00', '2023-12-19 17:00:00'),
	   ('2', '2', '2023-12-31 16:00:00', '2023-12-31 17:00:00', '2023-12-31 16:00:00', '2023-12-31 17:00:00');

