-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 11:42:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pianoroom` ;

-- -----------------------------------------------------
-- Schema booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pianoroom` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pianoroom` ;

-- -----------------------------------------------------
-- Table `pianoroom`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`USER` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`USER` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `major` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pianoroom`.`ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`ROOM` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`ROOM` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pianoroom`.`RESERVATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`RESERVATION` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`RESERVATION` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_user_id_idx` (`user_id` ASC),
  INDEX `fk_reservation_room_id_idx` (`room_id` ASC),
  CONSTRAINT `fk_reservation_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `pianoroom`.`USER` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `pianoroom`.`ROOM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pianoroom`.`BUSINESS_HOUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`BUSINESS_HOUR` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`BUSINESS_HOUR` (
  `id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `day_of _week` VARCHAR(45) NOT NULL,
  `opening_time` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_businesshr_room_id_idx` (`room_id` ASC),
  CONSTRAINT `fk_businesshr_room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `pianoroom`.`ROOM` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pianoroom`.`CHECKRECORD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pianoroom`.`CHECKRECORD` ;

CREATE TABLE IF NOT EXISTS `pianoroom`.`CHECKRECORD` (
  `id` INT NOT NULL,
  `reservation_id` INT NOT NULL,
  `checkin` DATETIME NULL,
  `checkout` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_checkrecord_id_idx` (`reservation_id` ASC),
  CONSTRAINT `fk_checkrecord_id`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `pianoroom`.`RESERVATION` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
